CREATE DATABASE IF NOT EXISTS form;
USE form;

DROP TABLE STUDENTI;

CREATE TABLE STUDENTI (
  IDSTUDENTE INTEGER NOT NULL AUTO_INCREMENT, 
  COGNOME VARCHAR(20), 
  NOME VARCHAR(20), 
  COMUNE VARCHAR(20), 
  CLASSE VARCHAR(20),
  PRIMARY KEY (IDSTUDENTE)
 );